### ISSUE TITLE
Python3 :(

### ISSUE THREAD

**Issue by merriam** [zestyping/q#18]
Really, some of use it....

Anyone have a quick port?

**Comment by jleclanche** [comment]
Can this be closed? I think with 2.5 the fixes are in, right?

**Comment by jleclanche** [comment]
Actually, why is 2.5 on pypi when it's not on master?

**Comment by mithro** [comment]
@jleclanche I've merged the pull request which released version 2.5 - I was waiting for @zestyping to do the merge but it seems he has been too busy.

**Comment by jleclanche** [comment]
@mithro Don't you have write access to this repo?

**Comment by mithro** [comment]
@jleclanche Yes, but I like to have a second person review my work before merging.

Looking at adding a quick test to make sure q works under Python 3 before closing.

**Comment by jleclanche** [comment]
Ok. I hope this can be taken care of soon though, as q is massively useful and having the repo fall behind is a huge shame!

FWIW I can review it if you cc me on it.

**Comment by mithro** [comment]
@jleclanche see https://github.com/zestyping/q/pull/23

**Comment by mithro** [comment]
I believe this is fixed now. Working on the issue @jleclanche identified at https://github.com/zestyping/q/issues/19
