### ISSUE TITLE
In master with python 3, accessing self attributes messes with the argument order

### ISSUE THREAD

**Issue by jleclanche** [zestyping/q#19]
Eg:

```
 0.3s getProperty: self, self.=<Weapon ('Fiery War Axe')>,
      data=<fireplace.xmlcard.XMLCard object>, prop='atk', ret, self.=0,
      slots=[]
```

This was from a call to self=, self.data=, prop=, ret=, self.slots=. The names are all mixed up every call to self.

**Comment by jleclanche** [comment]
@mithro ping again

**Comment by mithro** [comment]
@jleclanche I took your test and added it in https://github.com/mithro/q/commit/8dfb6cf7a0229eb85485c54eca6c09687d8294fa#diff-228ad81eb9d9774ab706a83b69e3dd5eR63

I've confirmed it passes on Python 2 and fails on Python 3. Just waiting for what travis shows me at https://travis-ci.org/mithro/q/builds/66159323

**Comment by mithro** [comment]
Actually that should have been https://travis-ci.org/mithro/q/builds/66160170

@jleclanche Any thoughts on what needs to be done to fix the issue?

**Comment by jleclanche** [comment]
No idea sorry, this is way beyond me.

**Comment by mithro** [comment]
I think this is a Python bug - see https://bugs.python.org/issue21295
