### ISSUE TITLE
Wrong log file

### ISSUE THREAD

**Issue by M0rtenB** [zestyping/q#33]
My q file shows up in /var/folders/nm/hz6r1lss5wg0l0l954nlwq080000gn/T/q instead of /tmp/q
Using brewed Python 3.5.0 on OSX Capitan GM.

**Comment by mithro** [comment]
Do you have any of TMPDIR or TEMP set in your environment?

**Comment by M0rtenB** [comment]
Well, yes. I'll show myself out.
