### ISSUE TITLE
Full text in /tmp/q ?

### ISSUE THREAD

**Issue by JPFrancoia** [zestyping/q#38]
Hi,

I find q awesome. It's a great tool.

Is there a way to get a full output in /tmp/q ? When I try to print a long string, it is a cut, and replaced in the middle with "...'.

Thanks !

**Comment by zestyping** [comment]
Hi,

Whenever it does that it should write the full output into a temporary file
for you.  At the end of the line in /tmp/q, it should give the name of the
file in parentheses.

**Comment by JPFrancoia** [comment]
Really ? I just get that:

```bash
cat /tmp/q

 0.0s spawn_sudo: 
      os.environ=environ({'TERM': 'xterm-256color', 'SHELL': '/us...y.linux-x86_64/eskytester-0.1.linux-x86_64/tcl'})
```

**Comment by zestyping** [comment]
Oh, I see what you mean.  Yeah, unfortunately q is not smart enough to do
this for structures like that, only for long strings.  It would be a good
improvement.

**Comment by mithro** [comment]
Somewhere there is a patch floating around which adds this functionality. I
haven't had time to test it so it hasn't been merged.

**Comment by JPFrancoia** [comment]
Ah ok, I haven't used long strings yet. No problem guys, I'll stay in standby !

**Comment by mithro** [comment]
The fact that the last patch has been floating around for more then ~6 months means I wouldn't wait for either myself or @zestyping to get it working :-)

Will happily merge any pull request with tests :-)

**Comment by JPFrancoia** [comment]
I'll try to do it if I can find time these days. Can I use pytest for the tests ?

**Comment by mithro** [comment]
Existing tests are at https://github.com/zestyping/q/blob/master/test/test_basic.py -- As you can see they are pretty basic so far...

**Comment by JPFrancoia** [comment]
Yep, and they use unitest, which is a PIA.

**Comment by jnak** [comment]
Just discovered the tool today. It's awesome. I definitely +1 this :)
