### ISSUE TITLE
Remove allow_failure in .travis.yml once a pep8 which runs on Python 3.6 is released 

### ISSUE THREAD

**Issue by mithro** [zestyping/q#42]
https://github.com/zestyping/q/blob/master/.travis.yml#L13

Python nightly is currently failing because the released pep8 requires getargspec which has been removed in Python 3.6, a patch is already in pep8 but it hasn't been released yet.

Remove this line once a pep8 which includes  https://github.com/PyCQA/pep8/commit/c86685a3fe0ff0b6f813d90677f67a4faf662791

**Comment by bilderbuchi** [comment]
drive-by comment: The linked fix has been published in the already-released pycodestyle version 1.7.0, afaict.

**Comment by zestyping** [comment]
Done!
