### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by SnoopJeDi** [zestyping/q#66]
The last release of `q` to PyPI was version `2.6` in 2015, but there have been [a number of changes](https://github.com/zestyping/q/compare/v2.6..master) since this release.

It is my understanding that [releases are still possible](https://github.com/zestyping/q/blame/master/CODESHELTER.md#L63-L64), is there any chance for a new release to bring these fixes and features to PyPI? :slightly_smiling_face:

**Comment by SnoopJeDi** [comment]
The specific feature that makes me think _"gosh I wish I could get that from PyPI"_ is the new default truncation behavior added by #60, for what it's worth.

**Comment by skorokithakis** [comment]
Ah, yes, I will see if I can make a new release, thanks!

**Comment by skorokithakis** [comment]
Uploaded 2.7!
